title: Mohit Kulkarni
description: AI researcher. Thinking about compute, cooperation, and intelligence.
url: "https://m2kulkarni.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

permalink: /blog/:title/

# GitHub Pages compatible
plugins:
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
